const actions = {
  SET_SEARCHED_HYMNS_LIST_OPEN: "SET_SEARCHED_HYMNS_LIST_OPEN",
  SET_DRAWER_OPEN: "SET_DRAWER_OPEN",
  SET_TITLE: "SET_TITLE",
  SET_LANGUAGE: "SET_LANGUAGE",
};

export default actions;
