export const GET_HYMNS_PREFIX = "hymns/GET_HYMNS";
export const GET_HYMNS_REQUEST_ACTION = GET_HYMNS_PREFIX + "_REQUEST_ACTION";
export const GET_HYMNS_SUCCESS_ACTION = GET_HYMNS_PREFIX + "_SUCCESS_ACTION";
export const GET_HYMNS_FAILURE_ACTION = GET_HYMNS_PREFIX + "_FAILURE_ACTION";

export const SET_HYMNS_PREFIX = "hymns/SET_HYMN";
export const SET_HYMNS_REQUEST_ACTION = SET_HYMNS_PREFIX + "_REQUEST_ACTION";
export const SET_HYMNS_SUCCESS_ACTION = SET_HYMNS_PREFIX + "_SUCCESS_ACTION";
export const SET_HYMNS_FAILURE_ACTION = SET_HYMNS_PREFIX + "_FAILURE_ACTION";

export const SAVE_HYMN_PREFIX = "hymns/SAVE_HYMN";
export const SAVE_HYMN_REQUEST_ACTION = SAVE_HYMN_PREFIX + "_REQUEST_ACTION";
export const SAVE_HYMN_SUCCESS_ACTION = SAVE_HYMN_PREFIX + "_SUCCESS_ACTION";
export const SAVE_HYMN_FAILURE_ACTION = SAVE_HYMN_PREFIX + "_FAILURE_ACTION";

export const ADD_HYMN_TO_HISTORY_PREFIX = "hymns/ADD_HYMN";
export const ADD_HYMN_TO_HISTORY_REQUEST_ACTION =
  ADD_HYMN_TO_HISTORY_PREFIX + "_REQUEST_ACTION";
export const ADD_HYMN_TO_HISTORY_SUCCESS_ACTION =
  ADD_HYMN_TO_HISTORY_PREFIX + "_SUCCESS_ACTION";
export const ADD_HYMN_TO_HISTORY_FAILURE_ACTION =
  ADD_HYMN_TO_HISTORY_PREFIX + "_FAILURE_ACTION";

export const DELETE_HYMN_PREFIX = "hymns/DELETE_HYMN";
export const DELETE_HYMN_REQUEST_ACTION =
  DELETE_HYMN_PREFIX + "_REQUEST_ACTION";
export const DELETE_HYMN_SUCCESS_ACTION =
  DELETE_HYMN_PREFIX + "_SUCCESS_ACTION";
export const DELETE_HYMN_FAILURE_ACTION =
  DELETE_HYMN_PREFIX + "_FAILURE_ACTION";
