export const GET_SETTINGS_PREFIX = "settings/GET_SETTINGS";
export const GET_SETTINGS_REQUEST_ACTION =
  GET_SETTINGS_PREFIX + "_REQUEST_ACTION";
export const GET_SETTINGS_SUCCESS_ACTION =
  GET_SETTINGS_PREFIX + "_SUCCESS_ACTION";
export const GET_SETTINGS_FAILURE_ACTION =
  GET_SETTINGS_PREFIX + "_FAILURE_ACTION";

export const UPDATE_SETTINGS_PREFIX = "settings/UPDATE_SETTINGS";
export const UPDATE_SETTINGS_REQUEST_ACTION =
  UPDATE_SETTINGS_PREFIX + "_REQUEST_ACTION";
export const UPDATE_SETTINGS_SUCCESS_ACTION =
  UPDATE_SETTINGS_UPDATEPREFIX + "_SUCCESS_ACTION";
export const UPDATE_SETTINGS_FAILURE_ACTION =
  UPDATE_SETTINGS_PREFIX + "_FAILURE_ACTION";
